title: ChiaPlottingServices.co.uk 
tagline: Chia Plotting Services
email: info@theplotstore.co.uk
description: >-
  This 
baseurl: ''
url: ''
author: itsmeaga1n
twitter:
  username: itsmeaga1n
  card: summary
plugins:
  - jekyll-seo-tag
markdown: kramdown
remote_theme: ItsMeaga1n/minimal-categorized
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/
  - node_modules
